name: mkbhd_clone
description: "MKBHD Clone in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.3
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  delightful_toast: ^1.1.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: LightFont
      fonts:
        - asset: assets/fonts/Moderustic-Light.ttf
        
    - family: RegularFont
      fonts:
        - asset: assets/fonts/Moderustic-Regular.ttf

    - family: MediumFont
      fonts:
        - asset: assets/fonts/Moderustic-Medium.ttf

